version: '3.4'

services: 
    db:
        image: postgres
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=db

    api:
        build:
            context: ./
            dockerfile: ./Dockerfile.api
        ports: 
            - 8080:8080
        environment: 
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_HOST=db
            - POSTGRES_DB=db
        depends_on: ['db']